# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bucketreactor', '0003_box_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
