language: python
services:
- docker
python:
- '3.6'
before_script:
- export LOCAL_POSTGRES_PORT_RANGE=5432
- docker-compose build
script:
- docker-compose run --rm web bash -c "python postgres_ready.py && ./manage.py migrate
  && ./manage.py test"
after_success:
- docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
- docker tag web registry.heroku.com/bucketreactor/web
- docker push registry.heroku.com/bucketreactor/web
notifications:
  email: true
cache:
  pip: true
deploy:
  provider: heroku
  api_key:
    secure: c8xC9Tn5C9Qi+btbvJS0FczNIaB1TRP7Mm2mzPbDR7y8n4L2JbLqcScZCOgEQMXcKyBG8InpsJ3Xv38TV/kVQDfSAc84NnvMeso2JXhiP38jZwT4x/Ps03xNgIrTml9ld4M5yBGpXX/48ifYywteHmQ2tQnSxubznzCnzH/FCFVaQw/jyVgIbIPAtNIb91n8S1CCW9ctzCfwXyIrIFy23dxj4njo8lV0Euz/CIDa2Jn9W+HyeUF+2Abf+nPNRyWRILK9lKkzM4H1iV9BMQcYYVoLc3Eh++ZTMsPUGmc1n0aTvPyyY+YiaJTnfDd/+kBV9f/6KRyIBXzPxE/C9aytt/HojPv9NoCN/y62IpZU21zyzJ7dNd6DzGu892qduVXcWQdxHlnv3FRhvEcrX6Jlki5Xbs8YQCiinK3kP6EPEesAwAlSvoRbHe5VTy0uLV+IPDEJ2wQAH7cC7pmZZ5WuaUJ5IS/sEEgNTD28mFTiHGI0ozBPAuSVrO55s7+Ut69zSiBPyE9blPZsNv6LAqKgbiv6ztJ+vPXisFuoOsQ2+/E80CgC1k4wHWWsL4sNOztx813OtauR7iTXzzdm0E+LhpA8Ta2HbtVh2BUFbM0DMtLjJ64b/tRxaX3F2KMzycvLUMmvSzB6AOXhUt8zho8JWM0fQy7Ovnrowi8hGlQZmQc=
  app: buckets
  on:
    repo: javadan/buckets
env:
  global:
    secure: w7H+X11qMlms7wZvgwZGY2vxSQ7rHDjCpVKIGdbSTD3VnbvW3UuxXrNvSjrckoXmBhjwjd2DaiwMbZzeH18vAf9Klx5lMj7kjeDxqABFvvWzBIqXjQzzXI0Y8JAZCmiix3Qm07T0E0EjTUpO2yWiNdkhtcP8wIqVC7x7VXWbqrKBbAL+ZkQnh5nAV1AS0sBkLGBmRN2J223U0MCiiv6/egf4jw1A5mL//aTXByCYqMH/9szCC+XyLkm7qkelKXin55HbD/lZEugoxif6zFkGRBBKc47sHSCyOo68sk6gJ+0qHXFnm+4/lKpRgCCBULBbuAlx22mqYC9al6m/sevVEZBndSa1mu09vgxWYY/LtEYAWgph9v/uNB4FACUbVrh1iX0hexlWyJ8efbNvjrnzIogApwycTb9XsMXIu1xczSX5WjOzQWwGfROc1BKxv5ku5uGd4bqcFMHEHFywop/dUjt5d/geDa6OtLMVeBR9cQvgyLxEzhBPmYl+CWcmMrGxY64qXcce4gEsg+6/YqYNoB0jaxxQ2+FU14TGFiQjUBThUBzyv8VSotySJlkG8ELlUHh/tWHyjRaJidKLQIOykMLowmwjXZg1OeHHFFrMDDlKclT+xOoqewIXHZQ9imVYLdK77qqzGuhue1vooN10jx3HZN+/N/jQ3ppiSBZke18=
