version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - "/var/run/postgres.sock:/var/run/postgres/postgres.sock"
      - "./data/postgres:/var/lib/postgresql/data" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=daniel@zoiz.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgres
  web:
    restart: always
    build: ./
    image: web
    environment:
      - DJANGO_SECRET=local
      - LOCAL_POSTGRES_HOST=postgres
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres
