# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import bucket.enums
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_auto_20180914_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('tag', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, db_index=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=5, max_digits=8)),
                ('soil_moisture', models.DecimalField(decimal_places=5, max_digits=8)),
                ('grow_light_state', models.BooleanField(default=True)),
                ('fans_state', models.BooleanField(default=True)),
                ('irrigation_state', models.BooleanField(default=True)),
                ('grow_schedule', enumfields.fields.EnumField(default='phase1', enum=bucket.enums.ScheduleType, max_length=50)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bucket.Box')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
